### ISSUE TITLE
Fail to download file from server

### ISSUE THREAD

**Issue by MozzartDevelopment** [karikera/ftp-kr#119]
Visual Studio Code v 1.31.0 (1.31.0) with ftp-kr v 1.3.16 on macOS Mojave v 10.14.2

When I try to download any file from the server, the specified file is loaded, but without content. The extension reconnects every few seconds and try again to download the file. However, all files are listed with the command ftp-cr: list

**Comment by pedroacacio** [comment]
Same problem here.

VS Code: 1.31.0
ftp-kr: 1.3.16
Ubuntu 16.04

**Comment by ivan770** [comment]
Got that problem too after 1.31.0 update.

**Comment by AndryWJ** [comment]
Problem too after 1.31.0
https://github.com/karikera/ftp-kr/issues/62

**Comment by wattmedia** [comment]
same problem here ...after 1.31.0 update

**Comment by Zenoo** [comment]
Same here ... 1.31.0

**Comment by LaThortilla** [comment]
some here ... in versión 1.3.16 

i am using next configuration:
{
    "host": "1********",
    "username": "w*****",
    "password": "*****",
    "remotePath": "/",
    "protocol": "sftp",
    "port": 22,
    "fileNameEncoding": "utf8",
    "autoUpload": false,
    "autoDelete": false,
    "autoDownload": false,
    "ignore": [
        "sftp-settings\\.json",
    ],
    "ignoreJsonUploadCaution": true
}

**Comment by wattmedia** [comment]
hi there .. the solution is to add: 
 "ignoreRemoteModification": true, 
in ftp-kr.json config file.

 After that the ftp will no longer check if the remote file is modified or not and it will upload the file.

**Comment by bebeGit** [comment]
Seems to me more like a workaround than a solution...

**Comment by AndryWJ** [comment]
I do not know what it is connected with, but it does not help me anymore. Endless download... Plugin is no longer updated?

**Comment by AndryWJ** [comment]
failed to solve the problem. When searching for alternatives, many ftp clients also turned out to be problematic. Rollback vscode version to 1.30 solved the problem! I'll sit on it while ftp plugins are repairing.

**Comment by bebeGit** [comment]
Yay, did that a week ago to get rid of the problem. The bug is still present in VSC 1.31.1.

**Comment by klarkc** [comment]
Workaround for ubuntu (if you're using ppa):

```bash
sudo apt-get install code=1.30.2-1546901646
sudo apt-mark hold code
```

to undo this changes:
```bash
sudo apt-mark unhold code
sudo apt-get update && sudo apt-get install code
```

**Comment by smboy86** [comment]
> hi there .. the solution is to add:
> "ignoreRemoteModification": true,
> in ftp-kr.json config file.
> 
> After that the ftp will no longer check if the remote file is modified or not and it will upload the file.

{
...
"ignoreRemoteModification" : true
}

it is work for me ~~ thank you ~

**Comment by klarkc** [comment]
It's still happening in vscode 1.33.1

**Comment by AndryWJ** [comment]
vscode 1.35 — Problem solved

**Comment by klarkc** [comment]
Confirm, solved in 1.35

**Comment by spmeesseman** [comment]
Downloading folders still does not work in 1.35...  It downloads the first file fine, but seems to think it wasnt successful, as it keeps retrying and then eventually fails

**Comment by kanavaz** [comment]
I am still facing this issues any solutions for this Thanks

**Comment by pedroacacio** [comment]
@kanavaz 
My tip for you is to try to use other plugin. I'm working with https://github.com/Microsoft/vscode-remote-release.
It works fine
