### ISSUE TITLE
File exist error

### ISSUE THREAD

**Issue by Arredatore** [karikera/ftp-kr#34]
Hi! 
Don't know were to ask, So will start issue.

Everything worked fine, before rebooting Windows, or maybe before the last update of Visual Studio, I'm not quite sure.
Now it gives mistake
![error](https://user-images.githubusercontent.com/834978/35184616-1e8ad63a-fe09-11e7-83a4-f34f59b353b5.jpg)
Will be very appreciated for help.

**Comment by karikera** [comment]
oh..  Thanks for report!

um..   Could you write ftp-kr.json config & Details about error?
It will help to fix bug!

I tried to fix the suspicious place in new update! (version 1.2.4)

**Comment by Arredatore** [comment]
You are fast! Thank you.

[Error]
message: \domains\cornices.studio\resources\views\welcome.blade.php is not in workspace
[Stack Trace]
Error: \domains\cornices.studio\resources\views\welcome.blade.php is not in workspace
	at ConfigClass.workpath (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\config.js:428:23)
	at FtpCacher.ftppath (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\ftpsync.js:73:93)
	at FtpCacher.<anonymous> (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\ftpsync.js:192:34)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\ftpsync.js:7:71)
	at Promise (<anonymous>)
	at __awaiter (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\ftpsync.js:3:12)
	at FtpCacher.ftpDownload (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\ftpsync.js:191:16)
	at QuickPickItem.util.Deferred.list.pick.item.pick.item [as onselect] (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\ftpsync.js:428:67)
	at QuickPick.<anonymous> (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\vsutil\vsutil.js:141:32)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\***\.vscode\extensions\ruakr.ftp-kr-1.2.3\out\vsutil\vsutil.js:4:58)
	at <anonymous>

**Comment by karikera** [comment]
I fixed about share folder path in 1.2.5 update!
Is it share folder?

**Comment by Arredatore** [comment]
I'm sorry I'll test on Monday only.

**Comment by Arredatore** [comment]
Hi! I've checked it still doesn't work for me. 
upload /domains/cornices.studio/resources/views/welcome.blade.php/welcome-fine.blade.php
upload fail: /domains/cornices.studio/resources/views/welcome.blade.php/welcome-fine.blade.php
Error: welcome.blade.php: File exists[550]

Interesting that it once made upload but created the folder with the name of the file and put the file there. Download always fail.

As I said before, I have changed nothing, just came the second day and had started the editor. There was an update of the editor as well that day.

**Comment by karikera** [comment]
I fixed about path error in 1.2.6 update!

**Comment by Arredatore** [comment]
Thank you that works now! Your plugin the only reason why I made attempt to change Netbeans by VC, without FTP client I will not even give it a try.

**Comment by karikera** [comment]
I am so glad!
