### ISSUE TITLE
altServer not working anymore 1.3.13

### ISSUE THREAD

**Issue by ash0803** [karikera/ftp-kr#65]
I can't target or ssh into altservers anymore. Works on the main server fine

**Comment by karikera** [comment]
Thanks for reporting!
I fixed that bug in new update! (1.3.14)

**Comment by ash0803** [comment]
Hmm... still doesn't work. I'm on Mac OS High Sierra if that helps.

Target doesn't bring up a selector like it did before and ssh now asks for a password although I'm using a non-password private key. My example config:

```
{
    "altServer": [
        {
            "name": "PROD",
            "host": "x.x.x.x",
            "privateKey": "/Users/me/.ssh/key-prod"
        }
    ],
    "host": "y.y.y.y",
    "username": "username",
    "privateKey": "/Users/me/.ssh/key-dev",
    "remotePath": "/",
    "protocol": "sftp",
    "port": 22,
    "fileNameEncoding": "utf8",
    "autoUpload": false,
    "autoDelete": false,
    "autoDownload": false,
    "ignore": [
        ".git",
        "/.vscode/"
    ]
}
```

**Comment by karikera** [comment]
I found mistake at SSH
But i don't know why target doesn`t works..

**Comment by karikera** [comment]
I fixed SSH problem in new update (1.3.15)
I changed little thing of target command..  but i'm not sure it will works

**Comment by ash0803** [comment]
Ok so I found something that may be interesting.

- if main server host is an IP address then I won't be able to choose the alt servers with either target or ssh command
- I'm not able to use the cancel all function to stop a connection using the ssh command where I'm pretty sure I could before. This is useful to me as some connections are only available over VPN and when I'm not connected to the VPN I just want to cancel.

Thanks for your efforts!

**Comment by karikera** [comment]
Couldn't you see any selection or error from `Target` command?
`Target` command is too simple to react to hostname
It looks like I needed to test with macOS.. 
It will take more time.. I do not have any mac machine..  :(

`Cancel All` command did not works with SSH Terminal before,  it's different process with VSCode
You can just close SSH Terminal..  I did not implement different way to disconnect it yet

**Comment by ash0803** [comment]
Hmm ok I think I know what it is. The IP address was nothing to do with it, you were right. I must have had different versions of the plugin in my vscode windows. Sorry for that.

If I am not able to connect to the main ip address on save of the config file (e.g. requires VPN or server doesn't exist anymore) then target or ssh will not show the alt servers. Hope that helps reproduce the problem better.

Regarding the `Cancel All` command, I thought it worked before with the SSH command but I'm probably mistaken again :)

**Comment by karikera** [comment]
Thanks! I fixed it!(1.3.16 update)
I moved the initial connection to end of loading task.
